const DEVELOPMENT_EXTERNAL_API = 'http://staging-api.tcgshowdown.com';
const CENTRIFUGE_URL = 'wss://staging-ws.tcgshowdown.com';
const ADMIN_URL = 'https://staging-admin.tcgshowdown.com';
const FIREBASE_API_KEY = 'AIzaSyBLuAgdc0FV36Ft0DkIfDsA7OVKFpdLtM4'
const FIREBASE_AUTH_DOMAIN = 'tcg-showdown.firebaseapp.com'
const FIREBASE_DATABASE_URL = 'https://tcg-showdown-default-rtdb.firebaseio.com'
const {
  REACT_APP_API_URL,
  REACT_APP_CENTRIFUGE_URL,
  REACT_APP_STRIPE_KEY,
  REACT_APP_PAYPAL_CLIENT_ID,
  REACT_APP_ADMIN_URL,
  REACT_APP_FIREBASE_API_KEY,
  REACT_APP_FIREBASE_AUTH_DOMAIN,
  REACT_APP_FIREBASE_DATABASE_URL,
  REACT_APP_RECAPTCHA_SITE_KEY,
  REACT_APP_CONTENTFUL_SPACE,
  REACT_APP_CONTENTFUL_ACCESS_TOKEN,
} = process.env;

export const AppConfig = {
  API_URL: REACT_APP_API_URL || DEVELOPMENT_EXTERNAL_API,
  ADMIN_URL: REACT_APP_ADMIN_URL || ADMIN_URL,
  CENTRIFUGE_URL: REACT_APP_CENTRIFUGE_URL || CENTRIFUGE_URL,
  FIREBASE_API_KEY: REACT_APP_FIREBASE_API_KEY,
  FIREBASE_AUTH_DOMAIN: REACT_APP_FIREBASE_AUTH_DOMAIN,
  FIREBASE_DATABASE_URL: REACT_APP_FIREBASE_DATABASE_URL,
  RECAPTCHA_SITE_KEY: REACT_APP_RECAPTCHA_SITE_KEY,
  CONTENTFUL_SPACE: REACT_APP_CONTENTFUL_SPACE,
  CONTENTFUL_ACCESS_TOKEN: REACT_APP_CONTENTFUL_ACCESS_TOKEN,
};

export const Local = {
  TOKEN: 'act',
  REFRESH_TOKEN: 'rt',
};

export const STRIPE_KEY =
  REACT_APP_STRIPE_KEY ||
  'pk_test_51ION0TJnbZdTeGmaFk73izubJ7TCeYJOqmst9AGlj2l3v0GNaADzRSmPJHqzQpx6odahOWK25q632S8NhvRaJa2300vPrzlUQl';


export const PAYPAL_CLIENT_ID =
  REACT_APP_PAYPAL_CLIENT_ID ||
  'AVwyaTa6I8sNPzV2_cyxswlGPMm0g7d8G3JcyftXQK0nZsG5GJ_jI9Mke2HMUt9YzhuIzZbE-UQ9kX5a';
